name: ease_injection
description: A simple dependency injection mechanism
version: 0.0.1
repository: https://github.com/isaukywhite/ease_injection

environment:
  sdk: ">=2.17.5 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
